### ISSUE TITLE
Adding orders table in Admin 

### ISSUE THREAD

**Issue by chloejncrdg** [chloejncrdg/happy-shawarma#1]
## Summary

An orders table must be created on the Admin dashboard page to give an overview of all the orders for the day. This will also help the admin to keep track of daily orders. 

## Example
![image](https://github.com/chloejncrdg/happy-shawarma/assets/107106352/14cd9fa1-3cce-4256-b06c-a3ec52c19877)

The table must be at the very top of the Admin dashboard page, right above the stats.

**Comment by jyjames** [comment]
naadd na
