### ISSUE TITLE
Admin dashboard CSS styling

### ISSUE THREAD

**Issue by chloejncrdg** [chloejncrdg/happy-shawarma#2]
## Summary

Add CSS to Admin dashboard

## Example
![image](https://github.com/chloejncrdg/happy-shawarma/assets/107106352/79be2282-d10e-445f-a096-7cad2a0885e5)
![image](https://github.com/chloejncrdg/happy-shawarma/assets/107106352/7841d2a7-c9cf-41b2-935c-25d77db35c5b)

**Comment by jyjames** [comment]
tapos na to
